---
services:
  bing-wallpaper-downloader:
    build: .
    volumes:
      - ./:/app/download
    environment:
      - LOG_TO_CONSOLE=true
      - TARGET_FOLDER=/app
      - CHECK_FREQUENCY_HOURS=24
      - LOG_CODE_VALUES=false