---
services:
  bingwallpaperdownloader:
    image: redbearddotdev/bingwallpaperdownloader
    user: 1000:1000
    volumes:
      - /opt/bingwallpaper:/app/target
    environment:
      - CHECK_FREQUENCY_HOURS=6
